<div class="container">
        <h2 class="h2"><?php echo $this->getPageTitle();?></h2>
        <div class="float-right">
            <a href="/post/create" class="btn btn-primary pull-right">
                New post
                <i class="glyphicon glyphicon-plus-sign"></i>
            </a>
        </div><br>
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget odio ut metus porta convallis. Curabitur enim est, 
            facilisis ac tristique non, dignissim condimentum mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, 
            per inceptos himenaeos. Phasellus accumsan vehicula ligula, a pellentesque lorem posuere sed. Maecenas et velit tempor, pretium mi ut,
            scelerisque sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sollicitudin, erat non placerat porta, 
            arcu velit porta purus, in hendrerit est urna at tortor. Maecenas quis imperdiet felis. Mauris nec mollis orci. 
            Vestibulum sagittis vestibulum leo, molestie condimentum mi scelerisque ac. 
            Pellentesque euismod sed nulla et hendrerit. In hac habitasse platea dictumst. 
            Fusce semper interdum nibh ac eleifend. Aenean vel dignissim nunc.
        </div>
    </div>
</div>