<div class="container">
    <div class="row">
        <h1 class="h1">
            <?php $this->getPageTitle();?>
        </h1>
    </div>
    <?php foreach ($this->view->posts as $post) : ?>
        <div class="row">
            <a href="/post/<?php echo $post->id;?>/show">
                <h3 class="h3"><?php echo $post->title;?></h3>
            </a>
            <p class="text-justify"><?php echo $post->content;?></p>
            <p class="text-right">
                <a href="/post/<?php echo $post->id;?>/edit" class="btn btn-warning btn-xs"><i class="glyphicon glyphicon-pencil">editar</i></a>
                <a href="/post/<?php echo $post->id;?>/delete" class="btn btn-danger btn-xs" onclick="return confirm('Deletar este Post?')"><i class="glyphicon glyphicon-remove-sign">excluir</i></a>
            </p>
        </div>
    <?php endforeach;?>
</div>