<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="/assets/css/style.css">
        <title> sancrisxadev Micro Framework</title>
    </head>
    <body>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
    </ul>
    <div class="container">
        <div class="row">
            <h1>Página não encontrada</h1>
        </div>
    </div>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.min.js"></script>
    </body>
</html>